export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const FETCH_CONTACTS_ASYNC = 'FETCH_CONTACTS_ASYNC';
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const SEARCH_CONTACTS = 'SEARCH_CONTACTS';
